import App from './app';
import React, { FC } from 'react';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import AppContextProvider from '@/context/BaseContext';
import '@/assets/styles/globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600']
});

export const metadata: Metadata = {
  title: 'Dilshan Ramesh | Mobile Engineer',
  description: 'Generated by create next app',
  applicationName: "Dilshan's Portfolio",
  authors: [
    {
      name: 'Dilshan Ramesh',
      url: 'https://dilshan97.github.io'
    }
  ],
  generator: "Next.js",
  referrer: "origin",
  viewport: {
    width: 'device-width',
    initialScale: 1
  },
  creator: 'Dilshan Ramesh',
  publisher: 'GitHub Pages',
  robots: {
    index: false,
    follow: false,
  }
}
interface RootLayoutProps {
  children: React.ReactNode;
}
const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AppContextProvider>
          <App children={children} />
        </AppContextProvider>
      </body>
    </html>
  )
}

export default RootLayout